generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Quest
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          quest
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, Translate, type, zone, race, status]
        max_per_page: 10
      filter:
        display: [type, race, status_id]
      form:    ~
      edit:    ~
      new:     ~
