generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, email_address, username, is_active, is_super_admin]
        fields:
          is_active: { label: "Active" }
          is_super_admin: { label: "Super Admin" }

      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
