peanutPage:
  actAs:
    Timestampable: 
    Sluggable:
      fields: [title]
    Sortable: 
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    title:
      type: string(255)
      notnull: true
    content:
      type: clob
      notnull: true
    excerpt:
      type: clob
    status:
      default: draft
      type: string
      notnull: true
      values: [draft,publish]
    author:
      type: integer
  relations:
    sfGuardUser:
      local: author
      foreign: id
