Quest:
  columns:
    name:
      type: string(150)
      notnull: true
    type:
      type: string(50)
      notnull: true
    zone_id:
      type: string(150)
      notnull: true
    race:
      type: string(150)
      notnull: true
    status_id:
      type: integer
      notnull: false
    comment_id:
      type: integer
      notnull: false
  relations:
    Trad:
      class: ClientString
      local: name
      foreign: name
      foreignType: one
      foreignAlias: Quest
    Status:
      class: Status
      local: status_id
      foreign: id
      foreignType: one
      foreignAlias: Quest
    Comments:
      class: Comments
      local: id
      foreign: quest_id
      type: many
ClientString:
  columns:
    name:
      type: string(150)
      notnull: true
    name_fr:
      type: string(500)
      notnull: true
Status:
  columns:
    name:
      type: string(150)
      notnull: true
Comments:
  actAs: [Timestampable]
  columns:
    quest_id:
      type: integer
      notnull: true
    content:
      type: string(1000)
      notnull: true
    author_id:
      type: integer
      notnull: true
  relations:
    Quest:
      class: Quest
      local: quest_id
      foreign: id
      type: one
      foreignAlias: Quests
    User:
      class: sfGuardUser
      local: author_id
      foreign: id
      type: one
      foreignAlias: Authors
